### ISSUE TITLE
Interaction QTL and AI

### ISSUE THREAD

**Issue by mikelove** [liangyy/mixqtl#6]
hi Yanyu,

We are very interested in trying out mixQTL on a dataset at UNC. 

Are you planning to add support for interaction terms? E.g. we are interested in detecting genes significant for the last term in this formula:

```
total count ~ C * exp(X beta) 
# with X defined by the following R formula
~condition + genotype + condition:genotype
```

likewise for allelic imbalance, e.g. cases where the allelic imbalance changes with respect to a condition, something like

```
log(allele1/allele2) = X beta
```

but with X again having a condition x genotype term, and here the condition main effect term drops out because it affects both alleles of the same sample equally.

**Comment by liangyy** [comment]
Hi @mikelove, 

Thanks for your interest in trying out mixQTL!

Currently, as you know, mixQTL does not support an interaction term. We (I and @hakyim) have not thought about adding an interaction term before but It sounds like an interesting functionality to add!

Here are some thoughts on the implementation side. As you suggested, we can run 
* `y_trc ~ 1 + X_trc + condition + condition:X_trc`
* `y_ase ~ X_ase + condition:X_ase`
I guess it might be easier (and straightforward) to start with `lm` in R. 
If it is too slow to run, maybe we should implement the matrix-form calculation. Even though It's not something on our to-do list, if you'd like, we are happy to assist with the implementation.

Thanks!

Yanyu

**Comment by mikelove** [comment]
Thanks Yanyu for the reply! I'll let you know what we end up trying.
